# Effect of the Economical Environment on the Preferences of Car Makes a Consumer Purchases

## Data Gathering

### Data Grab For Price of Stock or Crypto

The packages are not pre installed on the servers and will need to be pip installed. Open a terminal on Coursera and Input line below:

https://pypi.org/project/yfinance/

- pip install pandas_datareader

- pip install yfinance

In [38]:
from pandas_datareader import data as pdr
import yfinance as yf
import pandas as pd

yf.pdr_override()  # <== that's all it takes :-)

# initialization
# Dates
start_date = "2021-01-01"
end_date = "2022-04-30"
# Stocks_Crypto
# "TSLA" -> Tesla, "F" -> Ford, "BTC" -> Bitcoin, "CL=F" -> Crude Oil
s_c = ["BTC-USD","TSLA","F"]
# The data set can be srunk down by calling out a frame or multiple ["Open","High","Low","Close","Adj Close","Volume"]
col = ["Open","Close"]

# Example code for pulling the stock price as a downloaded dataframe
# Example for bitcoin
# data = pdr.get_data_yahoo("BTC-USD", start="2020-01-01", end="2022-04-30")

# Loop through all of the desired stocks and pull the data from the yahoo finance API
for index, stock in enumerate(s_c):
    data = pdr.get_data_yahoo(stock, start=start_date, end=end_date)[col]
    for item in col:
        temp_text = stock + "_" + item
        #print(temp_text)
        data = data.rename(columns={item: temp_text})
    #print(data)
    print(stock, index)
    if index == 0:
        df_data = data
    else:
        df_data = pd.merge(df_data,data, on=['Date'], how='outer')

display(df_data)

[*********************100%%**********************]  1 of 1 completed
BTC-USD 0
[*********************100%%**********************]  1 of 1 completed
TSLA 1
[*********************100%%**********************]  1 of 1 completed
F 2

,BTC-USD_Open,BTC-USD_Close,TSLA_Open,TSLA_Close,F_Open,F_Close
Date,,,,,,
2021-01-01,28994.009766,29374.152344,NaN,NaN,NaN,NaN
2021-01-02,29376.455078,32127.267578,NaN,NaN,NaN,NaN
2021-01-03,32129.408203,32782.023438,NaN,NaN,NaN,NaN
2021-01-04,32810.949219,31971.914062,239.820007,243.256668,8.81,8.52
2021-01-05,31977.041016,33992.429688,241.220001,245.036667,8.47,8.65
...,...,...,...,...,...,...
2022-04-25,39472.605469,40458.308594,326.323334,332.673340,14.91,15.19
2022-04-26,40448.421875,38117.460938,331.809998,292.140015,15.10,14.71
2022-04-27,38120.300781,39241.121094,299.526672,293.836670,14.79,14.85
2022-04-28,39241.429688,39773.828125,299.993347,292.503326,14.91,14.62
2022-04-29,39768.617188,38609.824219,300.750000,290.253326,14.59,14.16

### Import Vehicle Fuel Economy Dataset

The dataset is available in the following website

https://www.fueleconomy.gov/feg/ws/#ft9

In [ ]:
import pandas as pd

In [ ]:
raw_fuel_economy_df = pd.read_csv("https://www.fueleconomy.gov/feg/epadata/fuel prices.csv", low_memory=False)
raw_fuel_economy_df.head()

NameError: name 'pd' is not defined

In [ ]:
raw_fuel_economy_df.shape

(46565, 84)

### Opening Vehicle sales dataset

The dataset is available in the following website

https://www.kaggle.com/datasets/suraj520/car-sales-data

In [ ]:
raw_car_sales_df = pd.read_csv("car_sales_data.csv")
raw_car_sales_df.head()

,Date,Salesperson,Customer Name,Car Make,Car Model,Car Year,Sale Price,Commission Rate,Commission Earned
0,2022-08-01,Monica Moore MD,Mary Butler,Nissan,Altima,2018,15983,0.070495,1126.73
1,2023-03-15,Roberto Rose,Richard Pierce,Nissan,F-150,2016,38474,0.134439,5172.40
2,2023-04-29,Ashley Ramos,Sandra Moore,Ford,Civic,2016,33340,0.114536,3818.63
3,2022-09-04,Patrick Harris,Johnny Scott,Ford,Altima,2013,41937,0.092191,3866.20
4,2022-06-16,Eric Lopez,Vanessa Jones,Honda,Silverado,2022,20256,0.113490,2298.85

## Data Manipulation

### Imports

Imports that will be used for data manipulation

In [ ]:
from pandas_datareader import data as pdr
import yfinance as yf
import pandas as pd

In [ ]:
# copy the datset to keep the origanl
car_sales_df = raw_car_sales_df.copy()

NameError: name 'raw_car_sales_df' is not defined

In [ ]:
# put dates in datetime format and get the date of the first and last cars sold
car_sales_df["Date"] = pd.to_datetime(car_sales_df["Date"], format="%Y-%m-%d")
sales_start_date = car_sales_df["Date"].min().strftime("%Y-%m-%d")
sales_end_date = car_sales_df["Date"].max().strftime("%Y-%m-%d")

ValueError: time data "2022-08-01" doesn't match format "%Y%m%d", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
# Create a function to get the data from Yahoo Finance API
def get_market_data (ticker, start_date, end_date):
    
    yf.pdr_override()  # <== that's all it takes :-)

    # download dataframe
    # This is the yahoo name for oil Crude Oil Oct 23 (CL=F)
    df = pdr.get_data_yahoo(ticker, start=start_date, end=end_date)
    
    return df.reset_index()

In [ ]:
# Get the financial information about economical and crypto data

# Crude Oil prices dataframe
crude_oil_df = get_market_data("CL=F", sales_start_date, sales_end_date)

# Bitcoin Price dataframe
BTC_df = get_market_data("BTC-USD", sales_start_date, sales_end_date)

# SP500 dataframe
SP500_df = get_market_data("^GSPC", sales_start_date, sales_end_date)

# Dow Jones Industrial dataframe
DJI_df = get_market_data("^DJI", sales_start_date, sales_end_date)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=70337ec4-2598-4a20-9e82-38b4f4c44d51' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>